### ISSUE TITLE
Automate dump downloading

### ISSUE THREAD

**Issue by newsch** [organicmaps/wikiparser#12]
Find the latest dump, listed at <https://dumps.wikimedia.org/other/enterprise_html/runs/>.

Get the filenames for all supported languages: `{$LANG}wiki-NS0-${DATE}-ENTERPRISE-HTML.json.tar.gz`.

Download any that aren't already present.

`wget` handles redirects, retrying on temporary errors, and resuming partial downloads.

Extracting the links from the html could be done with a `sed` incantation, but wouldn't be very robust.

Alternatively, handle extracting the latest links in a subcommand of the rust program, and invoke that from a script.

**Comment by biodranik** [comment]
wget + (e)grep may be enough, for example, https://stackoverflow.com/questions/33474828/wget-extract-links-and-save-them-to-a-file

It would be great to reuse the already existing language config from the repo for the supported languages list (and reference/document it if necessary to add a new language).

Also, the dump may be not finished yet, like it's now (only languages till `m` are present): https://dumps.wikimedia.org/other/enterprise_html/runs/20230701/

**Comment by newsch** [comment]
If you're happy with that I'll try it :+1:

**Comment by newsch** [comment]
> It would be great to reuse the already existing language config from the repo for the supported languages list (and reference/document it if necessary to add a new language).

Do you mean [this languages.txt file](https://github.com/organicmaps/organicmaps/blob/master/data/languages.txt)?

**Comment by biodranik** [comment]
No, the config from this repo. For now, manual sync with the main repo is ok, but it is a good idea to create an issue for the future.
